# Chapter 6: Matrices 

## 6.1 Matrices 

**Creating matrices from the entries:**

In [78]:
A1 = [0.0 1.0 -2.3 .1;
     1.3 4.0 -.1 0.0;
     4.1 -1.0 0.0 1.7]

# same as: 
A2 = [0.0 1.0 -2.3 .1; 1.3 4.0 -.1 0.0; 4.1 -1.0 0.0 1.7]

A1 == A2

true

**Using size of matrix**

In [79]:
size(A) # total size 
size(A,1) # rows
size(A,2) # cols 

size(A), size(A,1), size(A,2)

((3, 4), 3, 4)

In [80]:
m, n = size(A)
m, n

(3, 4)

In [81]:
# functions to check what type of matrix 

tall(X) = size(X,1) > size(X,2)
wide(X) = size(X,1) < size(X,2)
square(X) = size(X,1) == size(X,2)

tall(A), wide(A), square(A)

(false, true, false)

**Indexing entries**

In [82]:
A[2,3] # get entry 2,3 of A 

0

In [83]:
A[1,3] = 7.5 # set entry 1,3 of A to 7.5 
A

InexactError: InexactError: Int64(7.5)

**Single index indexing** 

In [84]:
# for row i, col j, you can access matrix Z with a single index like Z[(j-1)*num_rows+j] 
# elements are ordered as: -1,-1,0,2,2,-3 -> COLUMN MAJOR 

twod_to_oned(i, j, num_rows) = (j-1)*num_rows+i

Z = [-1 0  2;
     -1 2 -3]

Z[5], Z[twod_to_oned(2, 2, 2)]

(2, 2)

**Equality of matrices**

In [85]:
B = copy(A)
A == B

true

In [86]:
B[2,2] = 0
B

3×4 Matrix{Int64}:
 -1  0   1  0
  2  0   0  1
  0  4  -2  1

In [87]:
A == B # returns whether or not A and B are equal

false

In [88]:
A .== B # creates a matrix whose entires are bool, depending on whether the corresponding entries are equal

3×4 BitMatrix:
 1  1  1  1
 1  0  1  1
 1  1  1  1

In [89]:
sum(A.==B) # gives the number of entires of A and B that are equal

11

**row and column vectors**

In [90]:
# n-vectors are the same as nx1 martrices

a = [-2.1 -3 0] # matrix type

1×3 Matrix{Float64}:
 -2.1  -3.0  0.0

In [91]:
b = [-2.1; -3; 0] # vector type 

3-element Vector{Float64}:
 -2.1
 -3.0
  0.0

In [92]:
size(b)

(3,)

In [93]:
size(a)

(1, 3)

**slicing and submatrices**

In [94]:
A = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]

3×4 Matrix{Int64}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [95]:
A[1:2,3:4] # submatrix of a

2×2 Matrix{Int64}:
 1  0
 0  1

In [96]:
A[:,3] # third column of A

3-element Vector{Int64}:
  1
  0
 -2

In [102]:
A[2,:] # second row of A, return as column vector (transpose of the row)

4-element Vector{Int64}:
  2
 -3
  0
  1

In [97]:
A

3×4 Matrix{Int64}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [98]:
A[size(A,1):-1:1, :] # Matrix A with row order reversed

3×4 Matrix{Int64}:
  0   4  -2  1
  2  -3   0  1
 -1   0   1  0

In [99]:
B = [ 1 -3 ; 2 0 ; 1 -2]
B[:] # using single indexing, we get a vector of ALL elements of A in column-major

6-element Vector{Int64}:
  1
  2
  1
 -3
  0
 -2

In [100]:
reshape(B,(2,3)) # we can reshape B into any shape as long as the dimensions match the # of elements,
# reshaping will be by COLUMN-major order

2×3 Matrix{Int64}:
 1   1   0
 2  -3  -2

In [101]:
reshape(B,(3,3))

DimensionMismatch: DimensionMismatch: new dimensions (3, 3) must be consistent with array size 6

**block matrices**

In [104]:
# use ; to stack matrices and space to do (horizontal) concatenation 

B = [ 0 2 3 ]; # 1x3 matrix
C = [ -1 ]; # 1x1 matrix
D = [ 2 2 1 ; 1 3 5]; # 2x3 matrix
E = [4 ; 4 ]; # 2x1 matrix

A = [B C;
     D E]

3×4 Matrix{Int64}:
 0  2  3  -1
 2  2  1   4
 1  3  5   4

**column and row interpretation of a matrix**

an $m x n$ matrix $A$ can be interpreted as a collection of $n$ $m$-vectors (its columns) or a collection of $m$ $n$-row vectors (its rows) 

Julia distinguishes between a matrix and an array of vectors
-  An array (or a tuple) of column vectors can be converted into a matrix using the horizontal concatenation function `hcat`
- `vcat` concatenates an array of arrays vertically. This is useful when constructing a matrix from its row vectors

In [112]:
a = [ [1., 2.], [4., 5.], [7., 8.] ] # array of 2-vectors
A = hcat(a...) # ... splits array a into its elements, same as hcat(a[1], a[2], a[3])

2×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0

In [115]:
A = vcat(a...)

6-element Vector{Float64}:
 1.0
 2.0
 4.0
 5.0
 7.0
 8.0

## 6.2 Zero and identity matrices

In [59]:
using LinearAlgebra
norm(A),sqrt(sum(A.^2))

(6.082762530298219, 6.082762530298219)