# Chapter 6: Matrices 

## 6.1 Matrices 

**Creating matrices from the entries:**

In [78]:
A1 = [0.0 1.0 -2.3 .1;
     1.3 4.0 -.1 0.0;
     4.1 -1.0 0.0 1.7]

# same as: 
A2 = [0.0 1.0 -2.3 .1; 1.3 4.0 -.1 0.0; 4.1 -1.0 0.0 1.7]

A1 == A2

true

**Using size of matrix**

In [79]:
size(A) # total size 
size(A,1) # rows
size(A,2) # cols 

size(A), size(A,1), size(A,2)

((3, 4), 3, 4)

In [80]:
m, n = size(A)
m, n

(3, 4)

In [81]:
# functions to check what type of matrix 

tall(X) = size(X,1) > size(X,2)
wide(X) = size(X,1) < size(X,2)
square(X) = size(X,1) == size(X,2)

tall(A), wide(A), square(A)

(false, true, false)

**Indexing entries**

In [82]:
A[2,3] # get entry 2,3 of A 

0

In [83]:
A[1,3] = 7.5 # set entry 1,3 of A to 7.5 
A

InexactError: InexactError: Int64(7.5)

**Single index indexing** 

In [84]:
# for row i, col j, you can access matrix Z with a single index like Z[(j-1)*num_rows+j] 
# elements are ordered as: -1,-1,0,2,2,-3 -> COLUMN MAJOR 

twod_to_oned(i, j, num_rows) = (j-1)*num_rows+i

Z = [-1 0  2;
     -1 2 -3]

Z[5], Z[twod_to_oned(2, 2, 2)]

(2, 2)

**Equality of matrices**

In [85]:
B = copy(A)
A == B

true

In [86]:
B[2,2] = 0
B

3×4 Matrix{Int64}:
 -1  0   1  0
  2  0   0  1
  0  4  -2  1

In [87]:
A == B # returns whether or not A and B are equal

false

In [88]:
A .== B # creates a matrix whose entires are bool, depending on whether the corresponding entries are equal

3×4 BitMatrix:
 1  1  1  1
 1  0  1  1
 1  1  1  1

In [89]:
sum(A.==B) # gives the number of entires of A and B that are equal

11

**row and column vectors**

In [90]:
# n-vectors are the same as nx1 martrices

a = [-2.1 -3 0] # matrix type

1×3 Matrix{Float64}:
 -2.1  -3.0  0.0

In [91]:
b = [-2.1; -3; 0] # vector type 

3-element Vector{Float64}:
 -2.1
 -3.0
  0.0

In [92]:
size(b)

(3,)

In [93]:
size(a)

(1, 3)

**slicing and submatrices**

In [120]:
A = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]

3×4 Matrix{Int64}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [95]:
A[1:2,3:4] # submatrix of a

2×2 Matrix{Int64}:
 1  0
 0  1

In [96]:
A[:,3] # third column of A

3-element Vector{Int64}:
  1
  0
 -2

In [102]:
A[2,:] # second row of A, return as column vector (transpose of the row)

4-element Vector{Int64}:
  2
 -3
  0
  1

In [121]:
A

3×4 Matrix{Int64}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [123]:
#A[size(A,1):-1:1, :] # Matrix A with row order reversed
A[end:-1:1, :] # Matrix A with row order reversed

3×4 Matrix{Int64}:
  0   4  -2  1
  2  -3   0  1
 -1   0   1  0

In [124]:
B = [ 1 -3 ; 2 0 ; 1 -2]
B[:] # using single indexing, we get a vector of ALL elements of A in column-major

6-element Vector{Int64}:
  1
  2
  1
 -3
  0
 -2

In [125]:
reshape(B,(2,3)) # we can reshape B into any shape as long as the dimensions match the # of elements,
# reshaping will be by COLUMN-major order

2×3 Matrix{Int64}:
 1   1   0
 2  -3  -2

In [126]:
reshape(B,(3,3))

DimensionMismatch: DimensionMismatch: new dimensions (3, 3) must be consistent with array size 6

**block matrices**

In [127]:
# use ; to stack matrices and space to do (horizontal) concatenation 

B = [ 0 2 3 ]; # 1x3 matrix
C = [ -1 ]; # 1x1 matrix
D = [ 2 2 1 ; 1 3 5]; # 2x3 matrix
E = [4 ; 4 ]; # 2x1 matrix

A = [B C;
     D E]

3×4 Matrix{Int64}:
 0  2  3  -1
 2  2  1   4
 1  3  5   4

**column and row interpretation of a matrix**

an $m x n$ matrix $A$ can be interpreted as a collection of $n$ $m$-vectors (its columns) or a collection of $m$ $n$-row vectors (its rows) 

Julia distinguishes between a matrix and an array of vectors
-  An array (or a tuple) of column vectors can be converted into a matrix using the horizontal concatenation function `hcat`
- `vcat` concatenates an array of arrays vertically. This is useful when constructing a matrix from its row vectors

In [112]:
a = [ [1., 2.], [4., 5.], [7., 8.] ] # array of 2-vectors
A = hcat(a...) # ... splits array a into its elements, same as hcat(a[1], a[2], a[3])

2×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0

In [134]:
A = vcat(a...)
A = hcat(a...)'

3×2 adjoint(::Matrix{Float64}) with eltype Float64:
 1.0  2.0
 4.0  5.0
 7.0  8.0

## 6.2 Zero and identity matrices

**Zero matrices**

In [135]:
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

**identity matrices**

In [138]:
eye(n) = 1.0 * Matrix(I, n,n) # * 1.0 turns it from bool to float 

eye(4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

properties of Julia's identity matrix `I`:

In [143]:
# can deduce dimensions 
A = [1 -1 2; 0 3 -1]

2×3 Matrix{Int64}:
 1  -1   2
 0   3  -1

In [144]:
[A I]

2×5 Matrix{Int64}:
 1  -1   2  1  0
 0   3  -1  0  1

In [142]:
[A;I]

5×3 Matrix{Int64}:
 1  -1   2
 0   3  -1
 1   0   0
 0   1   0
 0   0   1

In [145]:
B = [ 1 2 ; 3 4 ]

2×2 Matrix{Int64}:
 1  2
 3  4

In [146]:
B + I 

2×2 Matrix{Int64}:
 2  2
 3  5

In [147]:
# ones matrices
ones(5,3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

**diagonal matrices** 

In [154]:
diagm([3,4,5]) # makes diagonal matrix 

3×3 Matrix{Int64}:
 3  0  0
 0  4  0
 0  0  5

In [155]:
H = [0 1 -2 1; 2 -1 3 0]
diag(H) # gets all the diagonal entries of the matrix and puts them into a vector

2-element Vector{Int64}:
  0
 -1

**random matrices**

In [157]:
rand(2,3) # uniform 
randn(3,2) # normal 

3×2 Matrix{Float64}:
  0.0147541   0.108395
  0.113235    0.600153
 -0.140001   -0.692441

**sparse matrices** 

In [163]:
using SparseArrays

rowind = [ 1, 2, 2, 1, 3, 4 ]; # row indexes of nonzeros
colind = [ 1, 1, 2, 3, 3, 4 ]; # column indexes
values = [-1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ]; # values
# above 3 vectors should all have same length

A = sparse(rowind, colind, values, 4, 5)

4×5 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -1.11    ⋅    1.17   ⋅     ⋅ 
  0.15  -0.1    ⋅     ⋅     ⋅ 
   ⋅      ⋅   -0.3    ⋅     ⋅ 
   ⋅      ⋅     ⋅    0.13   ⋅ 

In [165]:
nnz(A) # non zero entries

6

In [167]:
B = Array(A) # convert to matrix

4×5 Matrix{Float64}:
 -1.11   0.0   1.17  0.0   0.0
  0.15  -0.1   0.0   0.0   0.0
  0.0    0.0  -0.3   0.0   0.0
  0.0    0.0   0.0   0.13  0.0

In [187]:
A = sparse([1, 3, 2, 1], [1, 1, 2, 3], [1.0, 2.0, 3.0, 4.0], 3, 3)
B = Array(A)
B[1,3] = 0.0
sparse(B) # convert back to sparse 

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   3.0   ⋅ 
 2.0   ⋅    ⋅ 

In [174]:
spzeros(5,5) # sparse matrix all 0s 

5×5 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 

In [176]:
sparse(1.0I, n,n) # sparse identity 

4×4 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [190]:
speyee(n) = sparse(1.0I, n,n) # sparse identity 
speyee(5)

5×5 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0

In [191]:
spdiagonal([1,2,3])

3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [192]:
spdiagonal2(x) = sparse(diagm(x))
spdiagonal2([1,2,3])

3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [198]:
spdiagonal3(x) = sparse([1:length(x);], [1:length(x);], x, length(x), length(x))
spdiagonal3([1,2,3])

3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [202]:
# d is density 
# sprand(m,n,d) , sprandn(m,n,d)
# The nonzero entries are chosen randomly, with about mnd of them nonzero.
A = sprand(10000,10000,10^-7)

10000×10000 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
⎡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠄⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎦

## 6.3 Transpose, addition, and norm

**transpose**

In [204]:
# A' is the transpose of A
H = [0 1 -2 1; 2 -1 3 0]

2×4 Matrix{Int64}:
 0   1  -2  1
 2  -1   3  0

In [205]:
H'

4×2 adjoint(::Matrix{Int64}) with eltype Int64:
  0   2
  1  -1
 -2   3
  1   0

**addition, subtraction, and scalar multiplication**

uses standard mathematical notation

In [206]:
U = [ 0 4; 7 0; 3 1]
V = [ 1 2; 2 3; 0 4]

U+V

3×2 Matrix{Int64}:
 1  6
 9  3
 3  5

In [209]:
2.2*U 

# we can also multiply a matrix on the right by a scalar
U*2.2

3×2 Matrix{Float64}:
  0.0  8.8
 15.4  0.0
  6.6  2.2

**elementwise operation**

Julia supports some operations that are not standard mathematical ones. \
For example, in Julia you can add or subtract a constant from a matrix, which carries out the operation on each entry.

Or elementwise multiply each element of A with respective element of B is A .* B

In [212]:
exp.(U)

3×2 Matrix{Float64}:
    1.0     54.5982
 1096.63     1.0
   20.0855   2.71828

In [213]:
U .* V

3×2 Matrix{Int64}:
  0  8
 14  0
  0  4

In [214]:
2.2 .+ U

3×2 Matrix{Float64}:
 2.2  6.2
 9.2  2.2
 5.2  3.2

**matrix norm**

\begin{align}
||A|| &= (\Sigma_{i=1}^{m}\Sigma_{j=1}^{n}A_{ij}^2)^{1/2}
\end{align}

often written as $||A||_F$

In [220]:
A = [2 3 -1; 0 -1 4]
using LinearAlgebra
norm(A),sqrt(sum(A.^2)), norm(A[:]) # same as the norm of the vector consisting of all elements of A (flattened A)


(5.5677643628300215, 5.5677643628300215, 5.5677643628300215)

**triangle inequality**

for matrices: $||A+B|| \leq ||A||+||B||$

In [221]:
A = [-1 0; 2 2]; B = [3 1; -3 2];
norm(A + B), norm(A) + norm(B)

(4.69041575982343, 7.795831523312719)

In [223]:
norm(A+B) <= norm(A) + norm(B)

true

## 6.4 matrix-vector multiplication

In [224]:
A = [0 2 -1; -2 1 1]
x = [2, 1, -1]

A*x

2-element Vector{Int64}:
  3
 -4

**difference matrix**

$(n-1)\times n$ matrix : 

\begin{align}
D &= \begin{bmatrix}
-1 & 1 & 0 & \dots & 0 & 0 & 0 \\
\\
0 & -1 & 1 & \dots & 0 & 0 & 0 \\
\\
  &    & \ddots & \ddots \\
  \\
 & & & \ddots & \ddots \\
 \\
 0 & 0 & 0 & \dots & -1 & 1 & 0 \\
 \\
 0 & 0 & 0 & \dots & 0 & -1 & 1 \\
\end{bmatrix}

\end{align}

In [234]:
difference_matrix(n) = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)];
# can also represent as sparse matrix 
sparse_difference_matrix(n) = [-speye(n-1) spzeros(n-1)] + [spzeros(n-1) speye(n-1)];


D = difference_matrix(4)
spD = sparse_difference_matrix(4)

3×4 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -1.0   1.0    ⋅    ⋅ 
   ⋅   -1.0   1.0   ⋅ 
   ⋅     ⋅   -1.0  1.0

In [235]:
D*[-1,0,2,1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

In [236]:
spD*[-1,0,2,1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

**running sum matrix** 

lower trianglular $n \times n$ matrix : elements on and below the diagonal = 1
\begin{align}
S &= \begin{bmatrix}
1 & 0 & 0 & \dots & 0 & 0 & 0 \\
\\
1 & 1 & 0 & \dots & 0 & 0 & 0 \\
\\
  &    & \ddots & \ddots \\
  \\
 & & & \ddots & \ddots \\
 \\
 1 & 1 & 1 & \dots & 1 & 1 & 0 \\
 \\
 1 & 1 & 1 & \dots & 1 & 1 & 1 \\
\end{bmatrix}
\end{align}

In [241]:
function running_sum(n)
    S = zeros(n,n)
    for i=1:n
        for j=1:i
            S[i,j]=1
        end
    end
    return S
end

S = running_sum(4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

In [242]:
S*[-1,1,2,0]

4-element Vector{Float64}:
 -1.0
  0.0
  2.0
  2.0

In [243]:
# alternative 
running_sum2(n) = tril(ones(n,n)) # tril sets elements above the diagonal to zero
running_sum2(4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

**vandermonde matrix**

*polynomial evaluation at multiple points*: \\
entries of n-vector $c$ are coefficients of polynomial degree $n-1$ or less: 
\begin{align}
p(t) &= c_1 + c_2t + \dots + c_{n-1}t^{n-2} + c_{n}t^{n-1}
\end{align}

Let $t_1,\dots ,t_m$ be $m$ numbers and $m$-vector $y$ where $y_i = p(t_i)$. \
Then, we have $y = Ac$, where A is $m \times n$ matrix:

\begin{align}
A &= \begin{bmatrix}
1 & t_1 & \dots & t_1^{n-2} & t_1^{n-1} \\
1 & t_2 & \dots & t_2^{n-2} & t_2^{n-1} \\
\vdots  & \vdots   & & \vdots & \vdots \\
\vdots  & \vdots   & & \vdots & \vdots \\
1 & t_m & \dots & t_m^{n-2} & t_m^{n-1} \\
\end{bmatrix}
\end{align}

Mutliplying vector $c$ by this matrix $A$ is the same as evaluating a polynomial w coefficients $c$ at $m$ points.

In [245]:
# takes m-vector t and number n (polynomial degree n-1) 
function vandermonde(t, n) 
    m = length(t)
    V = zeros(m,n)
    for i=1:m
        for j=1:n
            V[i,j] = t[i]^(j-1)
        end
    end
    return V
end

vandermonde([-1,0,0.5,1],5)

4×5 Matrix{Float64}:
 1.0  -1.0  1.0   -1.0    1.0
 1.0   0.0  0.0    0.0    0.0
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0

In [247]:
# alternative, use hcat 
vandermonde2(t,n) = hcat([t.^i for i=0:n-1]...)
vandermonde2([-1,0,0.5,1],5)

4×5 Matrix{Float64}:
 1.0  -1.0  1.0   -1.0    1.0
 1.0   0.0  0.0    0.0    0.0
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0

In [248]:
vandermonde([-1,0,0.5,1],5) == vandermonde2([-1,0,0.5,1],5)

true

## 6.5 complexity

**complexity of matrix-vector multiplication** should be 2mn flops (grows linearly with both m and n)

In [272]:
m = 1000; n = 10000;
println(m, ", ", n)
A = rand(m,n); x = rand(n);
@time y = A*x;
m = Int(m / 2); n = n * 2; # should be same time
println(m, ", ", n)
A = rand(m,n); x = rand(n);
@time y = A*x;
m = 5000; # should increase by factor of 10
println(m, ", ", n)
A = rand(m,n); x = rand(n);
@time y = A*x;

1000, 10000
  0.002860 seconds (1 allocation: 8.000 KiB)
500, 20000
  0.003104 seconds (1 allocation: 4.125 KiB)
5000, 20000
  0.030038 seconds (2 allocations: 39.172 KiB)


In [277]:
# increase of efficiency in sparse matrices 
n = 10^4;
D = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)];
x = randn(n);
@time y=D*x;
Ds = [-speye(n-1) spzeros(n-1)] + [spzeros(n-1) speye(n-1)];
@time y=Ds*x;

  0.013955 seconds (2 allocations: 78.172 KiB)
  0.000027 seconds (2 allocations: 78.172 KiB)


In [281]:
using SparseArrays
nnz(Ds)

19998