In [4]:
uvector(i,n) = [zeros(i-1); 1; zeros(n-i)];

uvector(1,3)

3-element Vector{Float64}:
 1.0
 0.0
 0.0

In [6]:
s = [uvector(1,3); uvector(2,3); uvector(3,3)]

9-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 1.0

# 1.4 Inner Product

In [11]:
x = [1,2,3]
y = [2,3,4]

x'*y

20

In [18]:
1 .^ (0:4)

5-element Vector{Int64}:
 1
 1
 1
 1
 1

In [19]:
c = [100,102,105] # cash flow 
r = 0.05 # rate (5% interest rate)
d = (1+r) .^ -(0:length(c)-1) 

3-element Vector{Float64}:
 1.0
 0.9523809523809523
 0.9070294784580498

In [20]:
c'*d # net present value

292.38095238095235

In [23]:
shares = [200,950,500,100,14800,300,1500,100,300,216.7412,3000,200,65]
p = [2.64, 154.63,16.08,174.99,3.53,184.86,176.45,214.29,182.81,446.34,4.43,231.81,179.69]

shares'*p # total portfolio value 

#length(shares) == length(p)

789686.6172079999